### ISSUE TITLE
Add a delete button for admins

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#20]
A delete button already exists on the "edit event" form, but it would be nice to provide a way for admins to quickly prune duplicate or spammy events easily from the list of events.

<img width="513" alt="Screen Shot 2019-09-28 at 1 47 45 PM" src="https://user-images.githubusercontent.com/3410149/65821134-427a6500-e1f7-11e9-83e9-69d915e4219b.png">

I'm envisioning a trash icon next to the pencil to immediately delete an event . The trash icon is already available using the `<icon name="trash">` Vue component.

**Comment by R3l4x3** [comment]
I'll take this 👍
