### ISSUE TITLE
Allow admins to filter by unapproved & deleted events

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#22]
Add a filter drop down in the right sidebar that would show just for admins.

A ["trashed" filter](https://github.com/imacrayon/eventsinwichita/blob/master/app/Filters/Trashed.php) already exists. The "unapproved" filter would be pretty similar.

**Comment by R3l4x3** [comment]
I'll take this 👍

**Comment by imacrayon** [comment]
That’s a good question. I think it will be easier for you to keep the date filter the way it is. We can try that for now and see how it feels then maybe provide more options later if it needs adjusting.
