### ISSUE TITLE
Provide a JSON API endpoint for events

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#28]
The endpoint URL can be something simple like `/api/events`. You should be able to filter by the same query string filters available on the homepage.

The controller for this endpoint can go here: `app/Http/Controllers/Api/EventController.php`

**Comment by raphaelz** [comment]
> The endpoint URL can be something simple like `/api/events`. You should be able to filter by the same query string filters available on the homepage.
> 
> The controller for this endpoint can go here: `app/Http/Controllers/Api/EventController.php`

I can take on this issue.

**Comment by lacasera** [comment]
@imacrayon do you mean something like this?
`api/events?after=2019-11-11 00:00:00&before=2019-10-18 00:00:0`

also should the endpoint be versioned?

**Comment by lacasera** [comment]
also should the event come from the local db or an external source

**Comment by imacrayon** [comment]
@lacasera yes, that example URL looks correct. The JSON info would come from the local database. The code will probably be similar to the `index` method in the [existing EventController](https://github.com/imacrayon/eventsinwichita/blob/5293c9bf4602194b33f6bb9a5f3c4b8a7fed518d/app/Http/Controllers/EventController.php#L13) except that it should  return a JSON response instead of an Inertia view

**Comment by lacasera** [comment]
pr to fix #28
