### ISSUE TITLE
Add meta data for Events

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#31]
Additional meta data on single event pages would be nice so that more info is provided when a like to an event is shared on social media/in slack maybe we should use [vue-meta](https://github.com/nuxt/vue-meta) to make this easy.

**Comment by thebatclaudio** [comment]
Hello, can I try to do this?

**Comment by imacrayon** [comment]
Yep!

**Comment by thebatclaudio** [comment]
Are you sure that vue-meta is the right choice? I think that we need a server side rendering, but vue-meta is client-side.

**Comment by imacrayon** [comment]
The front-end is build is build with [Inertia.js](https://inertiajs.com), so it's essentially a SPA. But you make a good point - I wonder if many services will be able to pull the meta info if JavaScript has to load first? I'm not sure if there's a way to edit the the meta data in the `app.blade.php` and still use Inertia.

**Comment by imacrayon** [comment]
The bottom of this page has meta tag examples: https://inertiajs.com/responses

**Comment by thebatclaudio** [comment]
We can try to use some of Prerending services that they suggests: https://inertiajs.com/server-side-rendering

**Comment by thebatclaudio** [comment]
Hi @imacrayon,
I think that I will proceed in this way:
- In app.blade.php I check if $meta is set, and if yes I print meta tags.
- We can use an associative array to declare meta tags, so we can the key for the attribute's name and the value for the attribute's content.

What do you think?

**Comment by imacrayon** [comment]
That sounds good to me 🙂

**Comment by thebatclaudio** [comment]
I made a pull request for this: #34 
I added only title and description in event's single page because I don't know exactly what metatags I have to show. If you want you can tell me and I will add them!

**Comment by imacrayon** [comment]
Fixed in #34
