### ISSUE TITLE
Pretty tag URLs

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#6]
Tag URLs currently look like this `https://eventsinwichita.com/?tags[]=7&tags[]=6`.

It would be cool if this were supported `https://eventsinwichita.com/?tags=7,6`.

It would be even better if this were supported `https://eventsinwichita.com/?tags=art,food`. Every tag has a URL slug in the database so this should be pretty straightforward to add.

**Comment by ghosh** [comment]
✋️ I can maybe help with this. I'll give it a go and submit a PR soon..

**Comment by ghosh** [comment]
@imacrayon You don't have any seed data. You think it would be possible for you to add some? It would make it easier to work with..

Alternatively, would you be ok mailing me a DB export? Without the users table if you wish..

**Comment by imacrayon** [comment]
Tags were removed in the new rewrite
