### ISSUE TITLE
Add embed Google Map on Places pages.

### ISSUE THREAD

**Issue by imacrayon** [imacrayon/eventsinwichita#7]
It would be cool to have a Google Map preview along with a place's address on pages like this http://eventsinwichita.dev/places/1

**Comment by handydani** [comment]
I'm interested in picking this one up, I did something similar at dtravie.com/emorinlaw. Is this what you're looking for?

**Comment by imacrayon** [comment]
I think eventually I'd like the map to have a different color scheme to better match the site, but I can create another issue for that when we get there.

**Comment by imacrayon** [comment]
Places have been removed for now in the rewrite
